### ISSUE TITLE
Issue starting SymBot / SyntaxError

### ISSUE THREAD

**Issue by humplemann** [3cqs-coder/SymBot#41]
Hey,

I am trying to make an initial setup of symbot. I followed the instructions:

- setup a new VM through Virtualization Station app on QNAP NAS
- used the latest stable release/ISO of Ubuntu server and did a fresh install
- from the SSH session I installed mongodb version 4.4 following this guide: https://apmb.co.uk/posts/mongodb-4.4-ubuntu-22-04/ (I did not install the latest mongodb because newer versions are not compatible with my CPU (core-dump error))
- I then installed NodeJS
- I then did a git clone from your repo + npm install
- From the configuration I just added the localhost entry for the mongodb URL

Then, when running npm start I receive the following error:

```
nm@symbot:~/SymBot$ npm start consolelog

> SymBot@0.99.1000-beta.0 start
> node symbot.js "consolelog"

/home/nm/SymBot/node_modules/mongoose/node_modules/mongodb/lib/admin.js:62
            session: options?.session,
                             ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/nm/SymBot/node_modules/mongoose/node_modules/mongodb/lib/index.js:6:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

The VM is running Ubuntu:

```
nm@symbot:~/SymBot$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```

I am running NodeJS:

```
nm@symbot:~/SymBot$ node -v
v12.22.9
```

This is my lshw:

```
nm@symbot:~/SymBot$ lshw -short
WARNING: you should run this program as super-user.
H/W path              Device      Class          Description
============================================================
                                  system         Computer
/0                                bus            Motherboard
/0/0                              memory         6GiB System memory
/0/1                              processor      Westmere E56xx/L56xx/X56xx (Nehalem-C)
/0/100                            bridge         440FX - 82441FX PMC [Natoma]
/0/100/1                          bridge         82371SB PIIX3 ISA [Natoma/Triton II]
/0/100/1/0                        system         PnP device PNP0b00
/0/100/1/1                        input          PnP device PNP0303
/0/100/1/2                        input          PnP device PNP0f13
/0/100/1/3                        storage        PnP device PNP0700
/0/100/1.1            scsi0       storage        82371SB PIIX3 IDE [Natoma/Triton II]
/0/100/1.1/0.0.0      /dev/cdrom  disk           QEMU DVD-ROM
/0/100/1.1/0.0.0/0    /dev/cdrom  disk
/0/100/1.1/0.0.0/0/1              volume         2029MiB data partition
/0/100/1.1/0.0.0/0/2              volume         15EiB Windows FAT volume
/0/100/1.1/0.0.0/0/3              volume         299KiB data partition
/0/100/1.3                        bridge         82371AB/EB/MB PIIX4 ACPI
/0/100/2              /dev/fb0    display        QXL paravirtual graphic card
/0/100/3                          network        Virtio network device
/0/100/3/0            ens3        network        Ethernet interface
/0/100/4                          bus            uPD720200 USB 3.0 Host Controller
/0/100/5                          communication  Virtio console
/0/100/5/0                        generic        Virtual I/O device
/0/100/6                          storage        Virtio block device
/0/100/6/0            /dev/vda    disk           Virtual I/O device
/0/100/7                          generic        Virtio memory balloon
/0/100/7/0                        generic        Virtual I/O device
/1                    input0      input          Power Button
/2                    input1      input          AT Translated Set 2 keyboard
/3                    input3      input          VirtualPS/2 VMware VMMouse
/4                    input4      input          VirtualPS/2 VMware VMMouse
/5                    input5      input          QEMU QEMU USB Tablet
WARNING: output may be incomplete or inaccurate, you should run this program as super-user.
```

Any ideas what the issue is?
Thanks!

**Comment by humplemann** [comment]
Closing issue, nodejs outdated. Updated to v21.x with no more issues.
